### ISSUE TITLE
HDR colors are washed out

### ISSUE THREAD

**Issue by wolfpld** [NVIDIA/egl-wayland#108]
With KDE 6 you can enable HDR for a display. If you do this on a display connected to an Nvidia GPU, the colors will be washed out, desaturated.

I have originally worked around this by connecting my HDR display to the AMD iGPU, and the colors were fine. Then, after a recent kernel update, the colors became washed out on AMD in the same way as on Nvidia. I believe the reason for this breakage is described here: https://gitlab.freedesktop.org/drm/amd/-/issues/3079#note_2339644

Is this a known issue in the Nvidia driver that is being worked on?

I am using nvidia 550.67.

Relevant drm_info data:

```
│   ├───Connector 2
│   │   ├───Type: DisplayPort
│   │   └───Properties
│   │       ├───"CRTC_ID" (atomic): object CRTC = 55
│   │       ├───"Colorspace": enum {Default, BT2020_RGB, BT2020_YCC} = BT2020_RGB
│   │       ├───"HDR_OUTPUT_METADATA": blob = 117
│   │       │   ├───Type: Static Metadata Type 1
│   │       │   ├───EOTF: SMPTE ST 2084 (PQ)
│   │       │   ├───Display primaries:
│   │       │   │   ├───Red: (0.6777, 0.3145)
│   │       │   │   ├───Green: (0.2715, 0.6328)
│   │       │   │   └───Blue: (0.1484, 0.0557)
│   │       │   ├───White point: (0.3135, 0.3291)
│   │       │   ├───Max display mastering luminance: 456 cd/m²
│   │       │   ├───Min display mastering luminance: 0.0673 cd/m²
│   │       │   ├───Max content light level: 456 cd/m²
│   │       │   └───Max frame average light level: 456 cd/m²

└───Planes
    ├───Plane 3
    │   └───Properties
    │       ├───"type" (immutable): enum {Overlay, Primary, Cursor} = Primary
    │       ├───"FB_ID" (atomic): object framebuffer = 114
    │       │   ├───Object ID: 114
    │       │   ├───Size: 3840x2160
    │       │   ├───Format: ABGR2101010 (0x30334241)
    │       │   ├───Modifier: NVIDIA_BLOCK_LINEAR_2D(h=5, k=6, g=2, s=1, c=0) (0x300000000606015)
    │       │   └───Planes:
    │       │       └───Plane 0: offset = 0, pitch = 15360 bytes
    │       ├───"CRTC_ID" (atomic): object CRTC = 55
    │       ├───"NV_INPUT_COLORSPACE": enum {None, IEC 61966-2-2 linear FP, ITU-R BT.2100-PQ YCbCr} = None
    │       ├───"NV_HDR_STATIC_METADATA": blob = 0
```

**Comment by erik-kz** [comment]
Thanks for the report. We are aware of the problem and are looking into it.

**Comment by cflewis** [comment]
Is there any news on this? It would be nice if I could utilize all the features of my 4090 :smile:

**Comment by bkdwt** [comment]
> Is there any news on this? It would be nice if I could utilize all the features of my 4090 😄

Install Windows and problem solved. 🙂

**Comment by ThePrestige8113** [comment]
> Is there any news on this? It would be nice if I could utilize all the features of my 4090 😄

How’s it looking?

**Comment by cubanismo** [comment]
Thank you for reporting this issue, and sorry for not following up sooner. We've been tracking it internally based on other, similar reports and believe it has been resolved by code changes that will be available in future driver branches, but are waiting on confirmation from our QA engineers that the fix resolves this particular issue as well. Once we've confirmed, we'll follow up with more specific release targets for the fix.

**Comment by thesword53** [comment]
The 565.57.01 beta driver fixes the issue. I tested HDR with KDE Wayland.

**Comment by XapaJIaMnu** [comment]
I am still having the issue. 565.57.01, open source driver , 3090, and LG - UltraGear 27GP950 4K Ultra HD 27" Nano IPS connected via display port. Could it be it doesn't work on some monitors? I will test another monitor tomorrow.

**Comment by XapaJIaMnu** [comment]
Sony TV A95L seems to work fine, hmmm

**Comment by XapaJIaMnu** [comment]
Not sure if anyone is monitoring this anymore, maybe @amshafer . 
I discovered that if i use the HDMI connection, i can use HDR with proper colours, but not through the displayport connection. Not entirely sure why. This is my drm_info grepping for HDR.

```
│   │   └───Properties
│   │       ├───"EDID" (immutable): blob = 131
│   │       ├───"DPMS": enum {On, Standby, Suspend, Off} = On
│   │       ├───"link-status": enum {Good, Bad} = Good
│   │       ├───"non-desktop" (immutable): range [0, 1] = 0
│   │       ├───"TILE" (immutable): blob = 0
│   │       ├───"CRTC_ID" (atomic): object CRTC = 57
│   │       ├───"Colorspace": enum {Default, BT2020_RGB, BT2020_YCC} = Default
│   │       ├───"HDR_OUTPUT_METADATA": blob = 0
│   │       └───"vrr_capable" (immutable): range [0, 1] = 1
│   ├───Connector 2

```
