### ISSUE TITLE
1.1.8 causes massive slowdown in opening new Alacritty windows

### ISSUE THREAD

**Issue by Hubro** [NVIDIA/egl-wayland#47]
The egl-wayland upgrade from 1.1.7 to 1.1.8 was identified to be the cause of the massive slowdown in opening new Alacritty windows here:

https://github.com/alacritty/alacritty/issues/5608

The verbose logs are provided in that bug report.

The relevant line is:

> [2021-11-14 12:51:44.031082609] [INFO ] [alacritty] Device pixel ratio: 1

Everything appears to freeze for 3-5 seconds right before this line.

I'm not sure how I can gather more information for troubleshooting, so please advise.

**Comment by yujiri8** [comment]
I would just like to confirm, as one of the other posters in that issue, that downgrading egl-wayland to 1.1.7 also fixed the issue for me.

Other info: I have Intel graphics, not Nvidia.

**Comment by erik-kz** [comment]
I think this is similar to an issue affecting QtQuick. Version 1.1.8 is likely interacting badly with this snippet of code from the Smithay client tool-kit https://github.com/Smithay/client-toolkit/blob/817ebb4c74dee7985411820e9c90fd09ea3e1027/src/event_loop.rs#L87

**Comment by VarLad** [comment]
I too am having the same issue

**Comment by VitalyAnkh** [comment]
It’s fixed by https://github.com/Smithay/client-toolkit/pull/214. Thanks to the great people! 🎉

**Comment by 1995parham** [comment]
The issue still exists on Alacritty which I think doesn't use Smithay.
