### ISSUE TITLE
Support multi-gpu mosaic

### ISSUE THREAD

**Issue by gilvbp** [NVIDIA/egl-wayland#91]
Is there schedule to fix wayland protocol/compositor issues? (https://download.nvidia.com/XFree86/Linux-x86_64/525.78.01/README/wayland-issues.html) 

Any plans to multi-gpu mosaic support ? 

Regards

**Comment by erik-kz** [comment]
Fixing such issues will involve collaboration with the community, so it's difficult to commit to a schedule since things aren't entirely within our control. Multi-GPU mosaic is definitely on the roadmap, and considered a high-priority features.

**Comment by gilvbp** [comment]
Thanks for the reply.
I'm worried about this because Gnome and others DE already have to plans to remove x11 session.

Reference:
https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/99

**Comment by gilvbp** [comment]
Hi @erik-kz, any updates on multi-gpu mosaic feature?

**Comment by erik-kz** [comment]
We're currently working on enabling multi-GPU support in EGL which represents one step towards supporting this feature.

**Comment by gilvbp** [comment]
> We're currently working on enabling multi-GPU support in EGL which represents one step towards supporting this feature.

Sounds great! Thanks for the info!

**Comment by gilvbp** [comment]
> We're currently working on enabling multi-GPU support in EGL which represents one step towards supporting this feature.

Hi Erik, Could you tell me when this should be ready?

**Comment by gilvbp** [comment]
@erik-kz, Is there any ETA on this?

**Comment by gilvbp** [comment]
Hi @erik-kz, any updates? Thanks

**Comment by gilvbp** [comment]
It is resolved on 560 drivers. https://forums.developer.nvidia.com/t/bug-wayland-egl-applications-not-working-with-dual-nvidia-gpus/285024/9

**Comment by xhertan** [comment]
This issue is not solved. I have a worksation with two Quadro RT5000 (NVLINK) with two screens and switching to wayland only display the pointer on the second screen. It works perfectly fine with X11. 
OS: Fedora 40 
NVIDIA Driver Version: 560.35.03

**Comment by gilvbp** [comment]
> This issue is not solved. I have a worksation with two Quadro RT5000 (NVLINK) with two screens and switching to wayland only display the pointer on the second screen. It works perfectly fine with X11. OS: Fedora 40 NVIDIA Driver Version: 560.35.03

Yes, you're right! I opened another issue here: https://github.com/NVIDIA/egl-wayland/issues/152

**Comment by gilvbp** [comment]
Good news! This feature will be fixed soon, ref: https://forums.developer.nvidia.com/t/wayland-support-for-the-565-release-series/312688

**Comment by gilvbp** [comment]
Closing, this will have to be supported by Vulkan Direct to Display and Wayland DE. Explanation here: https://forums.developer.nvidia.com/t/wayland-support-for-the-565-release-series/312688

**Comment by gilvbp** [comment]
@xhertan Hi on cosmic epoch is working fine, maybe sway too. They use vulkan (wlroots), not egl.

**Comment by gilvbp** [comment]
> > [@xhertan](https://github.com/xhertan) Hi, on cosmic epoch is working fine, maybe sway too. They use vulkan (wlroots), not egl.
> 
> @gilvbp Hi, Thanks for the info. But, I don't like Cosmic, it has not the quality level of Gnome has. Have you tried with KDE if this is working on it?

 Yes, I did, same problem. Kde uses egl, and it's an egl problem. You have to wait for the vulkan backend feature. https://invent.kde.org/plasma/kwin/-/merge_requests/5602 https://github.com/NVIDIA/egl-wayland/issues/152#issuecomment-2486895743.

**Comment by xhertan** [comment]
@gilvbp Hi, I tried cosmic and this is working fine for some minutes and it behaves as we reported, only displaying the pointer on the second screen.

**Comment by gilvbp** [comment]
> @gilvbp Hi, I tried cosmic and this is working fine for some minutes and it behaves as we reported, only displaying the pointer on the second screen. 

did you delete egl wayland package? You need to remove from the system. After that, sometimes, a few electrons apps and gtk3 apps could cause ( most of the cases on tilling mode using 2 window splits). If it occurs, just close and change the app on another monitor.

**Comment by gilvbp** [comment]
> [@gilvbp](https://github.com/gilvbp) Thanks for the info. I tried cosmic and it is unpleasant for me, so I will continue with gnome X11 that is working fine with the aforementioned configuration.

You're welcome.

**Comment by gilvbp** [comment]
> [@gilvbp](https://github.com/gilvbp) Thanks for the info. I tried cosmic and it is unpleasant for me, so I will continue with gnome X11 that is working fine with the aforementioned configuration.

@xhertan check this: https://github.com/NVIDIA/egl-wayland/issues/152#issuecomment-2541716835

**Comment by xhertan** [comment]
@gilvbp Thank you for the info. It looks like we will have KDE working with this soon. Hopefully, mutter can make the changes to get this working on gnome soon. Is there a report tracking this on mutter side to get this working on Gnome?

**Comment by gilvbp** [comment]
> @gilvbp Thank you for the info. It looks like we will have KDE working with this soon. Hopefully, mutter can make the changes to get this working on gnome soon. Is there a report tracking this on mutter side to get this working on Gnome? 

Here https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/4182

**Comment by gilvbp** [comment]
I'm finally closing this issue with the new driver release 570, it works with cosmic-epoch, so there is no more black screen egl bug.
